name: publish

on: [push]

jobs:
  publish-influxdb-grafana-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the influxdb-grafana Docker image
      run: |
        docker build . --tag ghcr.io/frepke/influxdb-grafana:latest
        docker run ghcr.io/frepke/influxdb-grafana:latest
        docker push ghcr.io/frepke/influxdb-grafana:latest
